project:
  type: website
  output-dir: public    # For https://myaseen208.com/misc
#  output-dir: docs     # For https://prupk.github.io/

website:
  title: "[MYaseen208](https://myaseen208.com/)"
  #logo: 
  #background: success
  search: true
  navbar:
    background: success
    left:
      - text: Blogs
        menu:
          - href: blogs.qmd
            text: "Blogs"
          - href: Shinylive.qmd
            text: "Shinylive in Quarto"
          - href: forms.qmd
            text: "Forms"
      - href: "https://myaseen208.com/urdu/"
        text: Urdu
      - href: about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, MYaseen208" 
    right: 
      - icon: github
        href: https://github.com/MYaseen208
      - icon: twitter 
        href: https://twitter.com/MYaseen208 
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual