lang: ar
dir: rtl
project:
  type: website
  output-dir: public   # For https://prupk.com/
#  output-dir: docs     # For https://prupk.github.io/

website:
  title: "اُردو"
  #logo: 
  #background: success
  search: true
  navbar:
    background: success
    right:
      - text: "شاعری"
        menu:
          - href: Behzad.qmd
            text: "بہزاد لکھنوی"
          - href: Naseer.qmd
            text: "نصیرالدین نصیرؔ"
      - href: about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, MYaseen208" 
    right: 
      - icon: github
        href: https://github.com/MYaseen208
      - icon: twitter 
        href: https://twitter.com/MYaseen208 
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual