project:
  type: website
  output-dir: docs     # For https://prupk.github.io/
# output-dir: public   # For https://prupk.com/

website:
  title: "PRU"
  logo: 
  background: success
  search: true
  navbar:
    background: success
    left:
      - href: home.qmd
        text: Home
      - text: "Team"
        menu:
          - href: about.qmd
            text: Team Lead
          - href: about.qmd
            text: RM & M&E Expert
          - href: about.qmd
            text: Data Analyst  .
      - href: about.qmd
        text: About
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
  page-navigation: true
  page-footer: 
    left: "Copyright 2022, PRU" 
    right: 
      - icon: github
        href: https://github.com/prupk
      - icon: twitter 
        href: https://twitter.com/pru_pk 
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual